# This is a basic workflow to help you get started with Actions

name: Arduino_compiler

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      # The matrix will produce one job for each defined configuration
      matrix:
        arduino-platform: ["arduino:samd", "arduino:avr"]
        # architecture 
        include:
          - arduino-platform: "arduino:samd"
            fqbn: "arduino:samd:nano_33_iot"
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:unowifi"
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
      - uses: actions/checkout@v2

      # install platform
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}

      # Runs a set of commands using the runners shell
      - name: Build Arduino
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqnb }}
          sketch-paths: |
            # configure action to search all folders
            - ./
          libraries: |
            - source-path: ./
